### ISSUE TITLE
convertToMGRSFromLatitude can fail

### ISSUE THREAD

**Issue by MavEtJu** [volkerv/GeoCoordinateConverter#1]
This:

    LatLon2MGRS *ll = [[LatLon2MGRS alloc] init];
    NSLog(@"%@", [ll convertToMGRSFromLatitude:-16.70462 Longitude:71.97212]);

Fails in calcDigraph:

-(NSString *) calcDigraph {

    int letter = floor((longitudeZoneValue - 1) * 8 + (eastingValue) / 100000.0);
    letter = letter - 24 * floor(letter / 24.0) - 1;

    NSString *digraph = (NSString *)[digraphArrayE objectAtIndex:letter];   <--- letter = -1
    
    letter = floor(northingValue / 100000.0);
    if (longitudeZoneValue / 2.0 == floor(longitudeZoneValue / 2.0)) {

This happens when letter is a multipe of 24:

    (lldb) p (longitudeZoneValue - 1) * 8 + (eastingValue) / 100000.0
    (double) $1 = 336.16972944582403
    (lldb) p 336 / 24.0
    (double) $4 = 14

**Comment by volkerv** [comment]
Thanks for reporting this issue.
It should be fixed now.

**Comment by MavEtJu** [comment]
Thank you!
